### ISSUE TITLE
not found ./diagram/history

### ISSUE THREAD

**Issue by bezrukovyura** [syncfusion/ej2-diagrams#1]
In last version error, on line 
`export * from './diagram/history';`
in diagram/index.ts

**Comment by Senthil-Dg** [comment]
Hi Bezrukov Yra.

We have missed to ship the ‘history.d.ts’ file on the specific location. However, we have resolved the reported issue. Please use the updated source files. 

Regards,
Kamesh R.

**Comment by bezrukovyura** [comment]
Thank you, problem solved.
